# Generated by Django 6.0.6 on 2026-06-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('EXPIRED', 'Expirada'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
